actors:
  manji0:
    image_url: /images/actors/manji0.jpg
    name: manji0
    url: https://twitter.com/_manji0
author: manji0
description: The podcast by Verda developers
description_long: |
  This is a random podcast show where people in a mysterious organization called Verda chat and talk about technologies that interest them.
email: request@verda.fm
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: verdafm
itunes_podcast_url:
keywords: verda,cloud,swe
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Verda FM
url: https://www.verda.fm
