actors:
  manji0:
    image_url: /images/actors/manji0.jpg
    name: manji0
    url: https://twitter.com/_manji0
author: manji0
description: The podcast by Verda developers
description_long: Verdaという謎の組織にいる人が雑談したり興味のある技術について話すラジオです。
email: request@verda.fm
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: verdafm
itunes_podcast_url:
keywords: verda,cloud,swe
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Verda FM
url: https://www.verda.fm
github:
  url: https://www.verda.fm
